version: '3.3'

services:
  weather:
    image: "weather"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/weather"
    volumes:
      - .:/usr/src/app/weather
    command: python3 -m main
    restart: always

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"